### ISSUE TITLE
can not find setup.py for pip install

### ISSUE THREAD

**Issue by chris-chris** [deepmind/rlax#2]
`pip install git+git://github.com/deepmind/rlax.git`

pip install is not working.
I think you missed pushing `setup.py`

```
$ pip install git+git://github.com/deepmind/rlax.git
Collecting git+git://github.com/deepmind/rlax.git
  Cloning git://github.com/deepmind/rlax.git to /private/var/folders/kv/x78mzwkd087567npnl1l3b200000gn/T/pip-req-build-nspn1ikj
  Running command git clone -q git://github.com/deepmind/rlax.git /private/var/folders/kv/x78mzwkd087567npnl1l3b200000gn/T/pip-req-build-nspn1ikj
    ERROR: Command errored out with exit status 1:
     command: /Users/chris/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/kv/x78mzwkd087567npnl1l3b200000gn/T/pip-req-build-nspn1ikj/setup.py'"'"'; __file__='"'"'/private/var/folders/kv/x78mzwkd087567npnl1l3b200000gn/T/pip-req-build-nspn1ikj/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/kv/x78mzwkd087567npnl1l3b200000gn/T/pip-req-build-nspn1ikj/pip-egg-info
         cwd: /private/var/folders/kv/x78mzwkd087567npnl1l3b200000gn/T/pip-req-build-nspn1ikj/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/chris/anaconda3/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/kv/x78mzwkd087567npnl1l3b200000gn/T/pip-req-build-nspn1ikj/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by mtthss** [comment]
Thanks Chris for raising this. We have now pushed the missing setup.py to the repo. Installing with pip directly from giithub should now work properly.
